; ==========================================================
; Enemies Data — auto-generated by json2asm.py
; Source: assets/enemies/enemies.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

; Enemy index reference:
;   0 = Octorok
;   1 = Moblin
;   2 = Keese
;   3 = Stalfos
;   4 = Tektite
;   5 = Leever
;   6 = Zora
;   7 = Darknut
;   8 = IronKnuckle
;   9 = Wizzrobe
;   10 = BubbleRed
;   11 = BubbleBlue
;   12 = BossHorsehead
;   13 = BossHelmethead
;   14 = BossRebonack
;   15 = BossCarock
;   16 = BossGooma
;   17 = BossBarba
;   18 = BossThunderbird
;   19 = BossDarkLink
; Total: 20 enemies

.export enemy_hp_table
enemy_hp_table:
    .byte $02  ; Octorok
    .byte $03  ; Moblin
    .byte $01  ; Keese
    .byte $03  ; Stalfos
    .byte $02  ; Tektite
    .byte $02  ; Leever
    .byte $03  ; Zora
    .byte $06  ; Darknut
    .byte $08  ; IronKnuckle
    .byte $04  ; Wizzrobe
    .byte $FF  ; BubbleRed
    .byte $FF  ; BubbleBlue
    .byte $10  ; BossHorsehead
    .byte $14  ; BossHelmethead
    .byte $18  ; BossRebonack
    .byte $14  ; BossCarock
    .byte $1C  ; BossGooma
    .byte $18  ; BossBarba
    .byte $20  ; BossThunderbird
    .byte $20  ; BossDarkLink

.export enemy_damage_table
enemy_damage_table:
    .byte $01  ; Octorok
    .byte $02  ; Moblin
    .byte $01  ; Keese
    .byte $02  ; Stalfos
    .byte $01  ; Tektite
    .byte $01  ; Leever
    .byte $02  ; Zora
    .byte $03  ; Darknut
    .byte $04  ; IronKnuckle
    .byte $03  ; Wizzrobe
    .byte $00  ; BubbleRed
    .byte $00  ; BubbleBlue
    .byte $04  ; BossHorsehead
    .byte $04  ; BossHelmethead
    .byte $05  ; BossRebonack
    .byte $04  ; BossCarock
    .byte $05  ; BossGooma
    .byte $05  ; BossBarba
    .byte $06  ; BossThunderbird
    .byte $04  ; BossDarkLink

.export enemy_speed_table
enemy_speed_table:
    .byte $01  ; Octorok
    .byte $01  ; Moblin
    .byte $02  ; Keese
    .byte $01  ; Stalfos
    .byte $02  ; Tektite
    .byte $01  ; Leever
    .byte $00  ; Zora
    .byte $01  ; Darknut
    .byte $01  ; IronKnuckle
    .byte $00  ; Wizzrobe
    .byte $02  ; BubbleRed
    .byte $02  ; BubbleBlue
    .byte $01  ; BossHorsehead
    .byte $01  ; BossHelmethead
    .byte $02  ; BossRebonack
    .byte $00  ; BossCarock
    .byte $01  ; BossGooma
    .byte $01  ; BossBarba
    .byte $02  ; BossThunderbird
    .byte $02  ; BossDarkLink

.export enemy_behavior_table
enemy_behavior_table:
    .byte $00  ; Octorok
    .byte $01  ; Moblin
    .byte $02  ; Keese
    .byte $03  ; Stalfos
    .byte $04  ; Tektite
    .byte $05  ; Leever
    .byte $06  ; Zora
    .byte $07  ; Darknut
    .byte $08  ; IronKnuckle
    .byte $09  ; Wizzrobe
    .byte $0A  ; BubbleRed
    .byte $0B  ; BubbleBlue
    .byte $80  ; BossHorsehead
    .byte $81  ; BossHelmethead
    .byte $82  ; BossRebonack
    .byte $83  ; BossCarock
    .byte $84  ; BossGooma
    .byte $85  ; BossBarba
    .byte $86  ; BossThunderbird
    .byte $87  ; BossDarkLink

.export enemy_drop_table
enemy_drop_table:
    .byte $00  ; Octorok
    .byte $01  ; Moblin
    .byte $00  ; Keese
    .byte $01  ; Stalfos
    .byte $00  ; Tektite
    .byte $00  ; Leever
    .byte $01  ; Zora
    .byte $02  ; Darknut
    .byte $03  ; IronKnuckle
    .byte $02  ; Wizzrobe
    .byte $FF  ; BubbleRed
    .byte $FF  ; BubbleBlue
    .byte $04  ; BossHorsehead
    .byte $04  ; BossHelmethead
    .byte $04  ; BossRebonack
    .byte $04  ; BossCarock
    .byte $04  ; BossGooma
    .byte $04  ; BossBarba
    .byte $04  ; BossThunderbird
    .byte $04  ; BossDarkLink
