; ==========================================================
; Metatiles Data — auto-generated by json2asm.py
; Source: assets/tilesets/cave_metatiles.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

; Metatile definitions: 28 entries
; Format: TL, TR, BL, BR tile indices + attribute byte
; Attribute byte: bits 0-1 = palette, bit 2 = solid, bit 3 = water, etc.

.export cave_metatiles_tl
cave_metatiles_tl:
    .byte $00  ; floor_dark
    .byte $01  ; floor_cave
    .byte $02  ; wall_rock_1
    .byte $03  ; wall_rock_2
    .byte $04  ; wall_rough
    .byte $05  ; wall_n
    .byte $02  ; wall_s
    .byte $07  ; wall_w
    .byte $02  ; wall_e
    .byte $19  ; corner_nw
    .byte $05  ; corner_ne
    .byte $07  ; corner_sw
    .byte $02  ; corner_se
    .byte $09  ; stalactite_small
    .byte $0A  ; stalactite_large
    .byte $00  ; stalagmite_small
    .byte $00  ; stalagmite_large
    .byte $0D  ; water_cave
    .byte $0E  ; water_edge_n
    .byte $0D  ; water_edge_s
    .byte $10  ; lava
    .byte $11  ; lava_anim
    .byte $12  ; lava_edge_n
    .byte $10  ; lava_edge_s
    .byte $15  ; rock_large
    .byte $1E  ; pebble_1
    .byte $1F  ; pebble_2
    .byte $1D  ; crack

.export cave_metatiles_tr
cave_metatiles_tr:
    .byte $00  ; floor_dark
    .byte $01  ; floor_cave
    .byte $02  ; wall_rock_1
    .byte $03  ; wall_rock_2
    .byte $04  ; wall_rough
    .byte $05  ; wall_n
    .byte $02  ; wall_s
    .byte $02  ; wall_w
    .byte $08  ; wall_e
    .byte $05  ; corner_nw
    .byte $1A  ; corner_ne
    .byte $02  ; corner_sw
    .byte $08  ; corner_se
    .byte $00  ; stalactite_small
    .byte $00  ; stalactite_large
    .byte $00  ; stalagmite_small
    .byte $00  ; stalagmite_large
    .byte $0D  ; water_cave
    .byte $0E  ; water_edge_n
    .byte $0D  ; water_edge_s
    .byte $10  ; lava
    .byte $11  ; lava_anim
    .byte $12  ; lava_edge_n
    .byte $10  ; lava_edge_s
    .byte $16  ; rock_large
    .byte $00  ; pebble_1
    .byte $00  ; pebble_2
    .byte $00  ; crack

.export cave_metatiles_bl
cave_metatiles_bl:
    .byte $00  ; floor_dark
    .byte $01  ; floor_cave
    .byte $02  ; wall_rock_1
    .byte $03  ; wall_rock_2
    .byte $04  ; wall_rough
    .byte $02  ; wall_n
    .byte $06  ; wall_s
    .byte $07  ; wall_w
    .byte $02  ; wall_e
    .byte $07  ; corner_nw
    .byte $02  ; corner_ne
    .byte $1B  ; corner_sw
    .byte $06  ; corner_se
    .byte $00  ; stalactite_small
    .byte $00  ; stalactite_large
    .byte $0B  ; stalagmite_small
    .byte $0C  ; stalagmite_large
    .byte $0D  ; water_cave
    .byte $0D  ; water_edge_n
    .byte $0F  ; water_edge_s
    .byte $10  ; lava
    .byte $11  ; lava_anim
    .byte $10  ; lava_edge_n
    .byte $13  ; lava_edge_s
    .byte $17  ; rock_large
    .byte $00  ; pebble_1
    .byte $00  ; pebble_2
    .byte $00  ; crack

.export cave_metatiles_br
cave_metatiles_br:
    .byte $00  ; floor_dark
    .byte $01  ; floor_cave
    .byte $02  ; wall_rock_1
    .byte $03  ; wall_rock_2
    .byte $04  ; wall_rough
    .byte $02  ; wall_n
    .byte $06  ; wall_s
    .byte $02  ; wall_w
    .byte $08  ; wall_e
    .byte $02  ; corner_nw
    .byte $08  ; corner_ne
    .byte $06  ; corner_sw
    .byte $1C  ; corner_se
    .byte $00  ; stalactite_small
    .byte $00  ; stalactite_large
    .byte $00  ; stalagmite_small
    .byte $00  ; stalagmite_large
    .byte $0D  ; water_cave
    .byte $0D  ; water_edge_n
    .byte $0F  ; water_edge_s
    .byte $10  ; lava
    .byte $11  ; lava_anim
    .byte $10  ; lava_edge_n
    .byte $13  ; lava_edge_s
    .byte $18  ; rock_large
    .byte $00  ; pebble_1
    .byte $00  ; pebble_2
    .byte $00  ; crack

.export cave_metatiles_attr
cave_metatiles_attr:
    .byte $00  ; floor_dark
    .byte $00  ; floor_cave
    .byte $04  ; wall_rock_1
    .byte $04  ; wall_rock_2
    .byte $04  ; wall_rough
    .byte $04  ; wall_n
    .byte $04  ; wall_s
    .byte $04  ; wall_w
    .byte $04  ; wall_e
    .byte $04  ; corner_nw
    .byte $04  ; corner_ne
    .byte $04  ; corner_sw
    .byte $04  ; corner_se
    .byte $00  ; stalactite_small
    .byte $00  ; stalactite_large
    .byte $04  ; stalagmite_small
    .byte $04  ; stalagmite_large
    .byte $08  ; water_cave
    .byte $08  ; water_edge_n
    .byte $08  ; water_edge_s
    .byte $18  ; lava
    .byte $18  ; lava_anim
    .byte $18  ; lava_edge_n
    .byte $18  ; lava_edge_s
    .byte $04  ; rock_large
    .byte $00  ; pebble_1
    .byte $00  ; pebble_2
    .byte $00  ; crack
