; ==========================================================
; Metatiles Data — auto-generated by json2asm.py
; Source: assets/tilesets/overworld_metatiles.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

; Metatile definitions: 35 entries
; Format: TL, TR, BL, BR tile indices + attribute byte
; Attribute byte: bits 0-1 = palette, bit 2 = solid, bit 3 = water, etc.

.export overworld_metatiles_tl
overworld_metatiles_tl:
    .byte $00  ; grass_plain
    .byte $01  ; grass_light
    .byte $02  ; grass_medium
    .byte $03  ; grass_dense
    .byte $04  ; dirt_path
    .byte $08  ; water_still
    .byte $09  ; water_anim
    .byte $0A  ; water_shore_n
    .byte $08  ; water_shore_s
    .byte $08  ; water_shore_e
    .byte $0D  ; water_shore_w
    .byte $0A  ; water_corner_nw
    .byte $0A  ; water_corner_ne
    .byte $0D  ; water_corner_sw
    .byte $5F  ; water_corner_se
    .byte $10  ; tree
    .byte $14  ; bush
    .byte $18  ; rock_large
    .byte $40  ; rock_small
    .byte $1C  ; mountain_wall_l
    .byte $1D  ; mountain_wall_r
    .byte $20  ; house_wall
    .byte $21  ; house_roof
    .byte $20  ; house_door
    .byte $28  ; bridge_h
    .byte $2C  ; bridge_v
    .byte $30  ; cave_entrance
    .byte $34  ; fence_h
    .byte $35  ; fence_v
    .byte $3C  ; sand
    .byte $44  ; flower
    .byte $4C  ; stairs_up
    .byte $54  ; sign_post
    .byte $6C  ; stone_tile
    .byte $41  ; tall_grass

.export overworld_metatiles_tr
overworld_metatiles_tr:
    .byte $00  ; grass_plain
    .byte $01  ; grass_light
    .byte $02  ; grass_medium
    .byte $03  ; grass_dense
    .byte $04  ; dirt_path
    .byte $08  ; water_still
    .byte $09  ; water_anim
    .byte $0A  ; water_shore_n
    .byte $08  ; water_shore_s
    .byte $0C  ; water_shore_e
    .byte $08  ; water_shore_w
    .byte $0A  ; water_corner_nw
    .byte $0A  ; water_corner_ne
    .byte $5E  ; water_corner_sw
    .byte $0C  ; water_corner_se
    .byte $11  ; tree
    .byte $15  ; bush
    .byte $19  ; rock_large
    .byte $00  ; rock_small
    .byte $1C  ; mountain_wall_l
    .byte $1D  ; mountain_wall_r
    .byte $20  ; house_wall
    .byte $22  ; house_roof
    .byte $20  ; house_door
    .byte $28  ; bridge_h
    .byte $2C  ; bridge_v
    .byte $31  ; cave_entrance
    .byte $34  ; fence_h
    .byte $35  ; fence_v
    .byte $3C  ; sand
    .byte $00  ; flower
    .byte $4C  ; stairs_up
    .byte $00  ; sign_post
    .byte $6C  ; stone_tile
    .byte $41  ; tall_grass

.export overworld_metatiles_bl
overworld_metatiles_bl:
    .byte $00  ; grass_plain
    .byte $01  ; grass_light
    .byte $02  ; grass_medium
    .byte $03  ; grass_dense
    .byte $04  ; dirt_path
    .byte $08  ; water_still
    .byte $09  ; water_anim
    .byte $08  ; water_shore_n
    .byte $0B  ; water_shore_s
    .byte $08  ; water_shore_e
    .byte $0D  ; water_shore_w
    .byte $0D  ; water_corner_nw
    .byte $5D  ; water_corner_ne
    .byte $0B  ; water_corner_sw
    .byte $0B  ; water_corner_se
    .byte $12  ; tree
    .byte $16  ; bush
    .byte $1A  ; rock_large
    .byte $00  ; rock_small
    .byte $1C  ; mountain_wall_l
    .byte $1D  ; mountain_wall_r
    .byte $20  ; house_wall
    .byte $20  ; house_roof
    .byte $23  ; house_door
    .byte $28  ; bridge_h
    .byte $2C  ; bridge_v
    .byte $32  ; cave_entrance
    .byte $34  ; fence_h
    .byte $35  ; fence_v
    .byte $3C  ; sand
    .byte $00  ; flower
    .byte $4C  ; stairs_up
    .byte $00  ; sign_post
    .byte $6C  ; stone_tile
    .byte $41  ; tall_grass

.export overworld_metatiles_br
overworld_metatiles_br:
    .byte $00  ; grass_plain
    .byte $01  ; grass_light
    .byte $02  ; grass_medium
    .byte $03  ; grass_dense
    .byte $04  ; dirt_path
    .byte $08  ; water_still
    .byte $09  ; water_anim
    .byte $08  ; water_shore_n
    .byte $0B  ; water_shore_s
    .byte $0C  ; water_shore_e
    .byte $08  ; water_shore_w
    .byte $5C  ; water_corner_nw
    .byte $0C  ; water_corner_ne
    .byte $0B  ; water_corner_sw
    .byte $0B  ; water_corner_se
    .byte $13  ; tree
    .byte $17  ; bush
    .byte $1B  ; rock_large
    .byte $00  ; rock_small
    .byte $1C  ; mountain_wall_l
    .byte $1D  ; mountain_wall_r
    .byte $20  ; house_wall
    .byte $20  ; house_roof
    .byte $20  ; house_door
    .byte $28  ; bridge_h
    .byte $2C  ; bridge_v
    .byte $33  ; cave_entrance
    .byte $34  ; fence_h
    .byte $35  ; fence_v
    .byte $3C  ; sand
    .byte $00  ; flower
    .byte $4C  ; stairs_up
    .byte $00  ; sign_post
    .byte $6C  ; stone_tile
    .byte $41  ; tall_grass

.export overworld_metatiles_attr
overworld_metatiles_attr:
    .byte $00  ; grass_plain
    .byte $00  ; grass_light
    .byte $00  ; grass_medium
    .byte $00  ; grass_dense
    .byte $00  ; dirt_path
    .byte $08  ; water_still
    .byte $08  ; water_anim
    .byte $08  ; water_shore_n
    .byte $08  ; water_shore_s
    .byte $08  ; water_shore_e
    .byte $08  ; water_shore_w
    .byte $08  ; water_corner_nw
    .byte $08  ; water_corner_ne
    .byte $08  ; water_corner_sw
    .byte $08  ; water_corner_se
    .byte $04  ; tree
    .byte $00  ; bush
    .byte $04  ; rock_large
    .byte $04  ; rock_small
    .byte $04  ; mountain_wall_l
    .byte $04  ; mountain_wall_r
    .byte $04  ; house_wall
    .byte $04  ; house_roof
    .byte $00  ; house_door
    .byte $00  ; bridge_h
    .byte $00  ; bridge_v
    .byte $00  ; cave_entrance
    .byte $00  ; fence_h
    .byte $00  ; fence_v
    .byte $00  ; sand
    .byte $00  ; flower
    .byte $00  ; stairs_up
    .byte $00  ; sign_post
    .byte $00  ; stone_tile
    .byte $00  ; tall_grass
