; ==========================================================
; Metatiles Data — auto-generated by json2asm.py
; Source: assets/tilesets/palace_metatiles.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

; Metatile definitions: 32 entries
; Format: TL, TR, BL, BR tile indices + attribute byte
; Attribute byte: bits 0-1 = palette, bit 2 = solid, bit 3 = water, etc.

.export palace_metatiles_tl
palace_metatiles_tl:
    .byte $00  ; floor_empty
    .byte $01  ; floor_plain
    .byte $02  ; floor_cracked
    .byte $03  ; floor_pattern
    .byte $6B  ; floor_decor_1
    .byte $6C  ; floor_decor_2
    .byte $04  ; wall_n
    .byte $08  ; wall_s
    .byte $06  ; wall_w
    .byte $08  ; wall_e
    .byte $08  ; wall_solid
    .byte $09  ; wall_corner_nw
    .byte $04  ; wall_corner_ne
    .byte $06  ; wall_corner_sw
    .byte $08  ; wall_corner_se
    .byte $0D  ; wall_brick
    .byte $10  ; door_closed
    .byte $11  ; door_open
    .byte $12  ; door_locked
    .byte $13  ; door_key
    .byte $14  ; pillar
    .byte $18  ; stairs_up
    .byte $19  ; stairs_down
    .byte $1C  ; pit
    .byte $20  ; torch_off
    .byte $21  ; torch_on
    .byte $24  ; statue
    .byte $28  ; chest_closed
    .byte $2A  ; chest_open
    .byte $2C  ; block_push
    .byte $69  ; water_dungeon
    .byte $6A  ; lava

.export palace_metatiles_tr
palace_metatiles_tr:
    .byte $00  ; floor_empty
    .byte $01  ; floor_plain
    .byte $02  ; floor_cracked
    .byte $03  ; floor_pattern
    .byte $00  ; floor_decor_1
    .byte $00  ; floor_decor_2
    .byte $04  ; wall_n
    .byte $08  ; wall_s
    .byte $08  ; wall_w
    .byte $07  ; wall_e
    .byte $08  ; wall_solid
    .byte $04  ; wall_corner_nw
    .byte $0A  ; wall_corner_ne
    .byte $08  ; wall_corner_sw
    .byte $07  ; wall_corner_se
    .byte $0D  ; wall_brick
    .byte $10  ; door_closed
    .byte $11  ; door_open
    .byte $12  ; door_locked
    .byte $13  ; door_key
    .byte $15  ; pillar
    .byte $18  ; stairs_up
    .byte $19  ; stairs_down
    .byte $1D  ; pit
    .byte $00  ; torch_off
    .byte $00  ; torch_on
    .byte $25  ; statue
    .byte $29  ; chest_closed
    .byte $2B  ; chest_open
    .byte $2C  ; block_push
    .byte $69  ; water_dungeon
    .byte $6A  ; lava

.export palace_metatiles_bl
palace_metatiles_bl:
    .byte $00  ; floor_empty
    .byte $01  ; floor_plain
    .byte $02  ; floor_cracked
    .byte $03  ; floor_pattern
    .byte $00  ; floor_decor_1
    .byte $00  ; floor_decor_2
    .byte $08  ; wall_n
    .byte $05  ; wall_s
    .byte $06  ; wall_w
    .byte $08  ; wall_e
    .byte $08  ; wall_solid
    .byte $06  ; wall_corner_nw
    .byte $08  ; wall_corner_ne
    .byte $0B  ; wall_corner_sw
    .byte $05  ; wall_corner_se
    .byte $0D  ; wall_brick
    .byte $10  ; door_closed
    .byte $11  ; door_open
    .byte $12  ; door_locked
    .byte $13  ; door_key
    .byte $16  ; pillar
    .byte $18  ; stairs_up
    .byte $19  ; stairs_down
    .byte $1E  ; pit
    .byte $00  ; torch_off
    .byte $00  ; torch_on
    .byte $26  ; statue
    .byte $00  ; chest_closed
    .byte $00  ; chest_open
    .byte $2C  ; block_push
    .byte $69  ; water_dungeon
    .byte $6A  ; lava

.export palace_metatiles_br
palace_metatiles_br:
    .byte $00  ; floor_empty
    .byte $01  ; floor_plain
    .byte $02  ; floor_cracked
    .byte $03  ; floor_pattern
    .byte $00  ; floor_decor_1
    .byte $00  ; floor_decor_2
    .byte $08  ; wall_n
    .byte $05  ; wall_s
    .byte $08  ; wall_w
    .byte $07  ; wall_e
    .byte $08  ; wall_solid
    .byte $08  ; wall_corner_nw
    .byte $07  ; wall_corner_ne
    .byte $05  ; wall_corner_sw
    .byte $0C  ; wall_corner_se
    .byte $0D  ; wall_brick
    .byte $10  ; door_closed
    .byte $11  ; door_open
    .byte $12  ; door_locked
    .byte $13  ; door_key
    .byte $17  ; pillar
    .byte $18  ; stairs_up
    .byte $19  ; stairs_down
    .byte $1F  ; pit
    .byte $00  ; torch_off
    .byte $00  ; torch_on
    .byte $27  ; statue
    .byte $00  ; chest_closed
    .byte $00  ; chest_open
    .byte $2C  ; block_push
    .byte $69  ; water_dungeon
    .byte $6A  ; lava

.export palace_metatiles_attr
palace_metatiles_attr:
    .byte $00  ; floor_empty
    .byte $00  ; floor_plain
    .byte $00  ; floor_cracked
    .byte $00  ; floor_pattern
    .byte $00  ; floor_decor_1
    .byte $00  ; floor_decor_2
    .byte $04  ; wall_n
    .byte $04  ; wall_s
    .byte $04  ; wall_w
    .byte $04  ; wall_e
    .byte $04  ; wall_solid
    .byte $04  ; wall_corner_nw
    .byte $04  ; wall_corner_ne
    .byte $04  ; wall_corner_sw
    .byte $04  ; wall_corner_se
    .byte $04  ; wall_brick
    .byte $04  ; door_closed
    .byte $00  ; door_open
    .byte $04  ; door_locked
    .byte $04  ; door_key
    .byte $04  ; pillar
    .byte $00  ; stairs_up
    .byte $00  ; stairs_down
    .byte $10  ; pit
    .byte $00  ; torch_off
    .byte $00  ; torch_on
    .byte $04  ; statue
    .byte $04  ; chest_closed
    .byte $00  ; chest_open
    .byte $04  ; block_push
    .byte $08  ; water_dungeon
    .byte $18  ; lava
