; ==========================================================
; Dialog Text Data — auto-generated by text2asm.py
; Source: /Users/jschmidt/lab/hub/.hub-data/projects/a79ec915-7144-4467-8392-2d2c0af9a18e/workspaces/e282a6f0-e601-4217-8efc-e1bc1e7d550c/zelda2b/assets/text/dialog.json
; DO NOT EDIT — regenerate from JSON source
; Encoding: tile indices. $FE=newline, $FF=end of dialog
; ==========================================================

.segment "PRG_FIXED_C"

; --- town_rauru ---
.export text_rauru_elder_1
text_rauru_elder_1:
    .byte $57, $45, $4C, $43, $4F, $4D, $45, $20, $54, $4F, $20, $52, $41, $55, $52, $55
    .byte $2E, $FE, $54, $48, $45, $20, $53, $4C, $45, $45, $50, $49, $4E, $47, $20, $5A
    .byte $45, $4C, $44, $41, $FE, $41, $57, $41, $49, $54, $53, $20, $49, $4E, $20, $54
    .byte $48, $45, $20, $4E, $4F, $52, $54, $48, $FE, $50, $41, $4C, $41, $43, $45, $2E
    .byte $FF

.export text_rauru_healer_1
text_rauru_healer_1:
    .byte $4C, $45, $54, $20, $4D, $45, $20, $48, $45, $41, $4C, $20, $59, $4F, $55, $52
    .byte $FE, $57, $4F, $55, $4E, $44, $53, $2E, $FF

.export text_rauru_hint_1
text_rauru_hint_1:
    .byte $54, $48, $45, $20, $43, $41, $4E, $44, $4C, $45, $20, $4C, $49, $47, $48, $54
    .byte $53, $FE, $44, $41, $52, $4B, $20, $43, $41, $56, $45, $53, $2E, $20, $53, $45
    .byte $45, $4B, $20, $49, $54, $FE, $49, $4E, $20, $54, $48, $45, $20, $46, $49, $52
    .byte $53, $54, $FE, $50, $41, $4C, $41, $43, $45, $2E, $FF

.export text_rauru_shop_1
text_rauru_shop_1:
    .byte $42, $55, $59, $20, $53, $4F, $4D, $45, $54, $48, $49, $4E, $47, $3F, $FF

.export text_rauru_woman_1
text_rauru_woman_1:
    .byte $49, $20, $48, $45, $41, $52, $44, $20, $4D, $4F, $4E, $53, $54, $45, $52, $53
    .byte $FE, $47, $52, $4F, $57, $20, $53, $54, $52, $4F, $4E, $47, $45, $52, $20, $49
    .byte $4E, $FE, $54, $48, $45, $20, $45, $41, $53, $54, $2E, $FF

; --- town_ruto ---
.export text_ruto_elder_1
text_ruto_elder_1:
    .byte $54, $48, $45, $20, $48, $41, $4D, $4D, $45, $52, $20, $43, $41, $4E, $FE, $42
    .byte $52, $45, $41, $4B, $20, $42, $4F, $55, $4C, $44, $45, $52, $53, $2E, $FE, $46
    .byte $49, $4E, $44, $20, $49, $54, $20, $49, $4E, $20, $50, $41, $4C, $41, $43, $45
    .byte $FE, $54, $57, $4F, $2E, $FF

.export text_ruto_hint_1
text_ruto_hint_1:
    .byte $41, $20, $52, $41, $46, $54, $20, $48, $49, $44, $45, $53, $20, $49, $4E, $FE
    .byte $54, $48, $45, $20, $54, $48, $49, $52, $44, $20, $50, $41, $4C, $41, $43, $45
    .byte $2E, $FE, $49, $54, $20, $43, $41, $4E, $20, $43, $52, $4F, $53, $53, $20, $54
    .byte $48, $45, $FE, $47, $52, $45, $41, $54, $20, $53, $45, $41, $2E, $FF

.export text_ruto_spell_1
text_ruto_spell_1:
    .byte $49, $20, $57, $49, $4C, $4C, $20, $54, $45, $41, $43, $48, $20, $59, $4F, $55
    .byte $FE, $54, $48, $45, $20, $4A, $55, $4D, $50, $20, $53, $50, $45, $4C, $4C, $2E
    .byte $FF

; --- town_saria ---
.export text_saria_elder_1
text_saria_elder_1:
    .byte $53, $41, $52, $49, $41, $20, $54, $4F, $57, $4E, $20, $57, $45, $4C, $43, $4F
    .byte $4D, $45, $53, $FE, $59, $4F, $55, $20, $42, $52, $41, $56, $45, $20, $48, $45
    .byte $52, $4F, $2E, $FF

.export text_saria_hint_1
text_saria_hint_1:
    .byte $54, $48, $45, $20, $42, $4F, $4F, $54, $53, $20, $4C, $45, $54, $20, $59, $4F
    .byte $55, $FE, $57, $41, $4C, $4B, $20, $4F, $4E, $20, $53, $48, $41, $4C, $4C, $4F
    .byte $57, $FE, $57, $41, $54, $45, $52, $2E, $FF

.export text_saria_spell_1
text_saria_spell_1:
    .byte $4C, $45, $41, $52, $4E, $20, $54, $48, $45, $20, $4C, $49, $46, $45, $FE, $53
    .byte $50, $45, $4C, $4C, $2E, $20, $49, $54, $20, $52, $45, $53, $54, $4F, $52, $45
    .byte $53, $FE, $59, $4F, $55, $52, $20, $48, $45, $41, $52, $54, $53, $2E, $FF

; --- town_mido ---
.export text_mido_elder_1
text_mido_elder_1:
    .byte $44, $45, $41, $54, $48, $20, $4D, $4F, $55, $4E, $54, $41, $49, $4E, $20, $49
    .byte $53, $FE, $46, $55, $4C, $4C, $20, $4F, $46, $20, $44, $41, $4E, $47, $45, $52
    .byte $2E, $FE, $42, $45, $20, $50, $52, $45, $50, $41, $52, $45, $44, $2E, $FF

.export text_mido_hint_1
text_mido_hint_1:
    .byte $54, $48, $45, $20, $46, $4C, $55, $54, $45, $20, $43, $41, $4E, $20, $43, $41
    .byte $4C, $4C, $FE, $41, $20, $57, $48, $49, $52, $4C, $57, $49, $4E, $44, $20, $54
    .byte $4F, $FE, $43, $41, $52, $52, $59, $20, $59, $4F, $55, $20, $46, $41, $52, $2E
    .byte $FF

.export text_mido_spell_1
text_mido_spell_1:
    .byte $54, $48, $45, $20, $46, $41, $49, $52, $59, $20, $53, $50, $45, $4C, $4C, $FE
    .byte $54, $52, $41, $4E, $53, $46, $4F, $52, $4D, $53, $20, $59, $4F, $55, $2E, $FE
    .byte $46, $4C, $59, $20, $54, $48, $52, $4F, $55, $47, $48, $20, $4C, $4F, $43, $4B
    .byte $45, $44, $FE, $44, $4F, $4F, $52, $53, $2E, $FF

; --- town_nabooru ---
.export text_nabooru_elder_1
text_nabooru_elder_1:
    .byte $54, $48, $45, $20, $43, $52, $4F, $53, $53, $20, $52, $45, $56, $45, $41, $4C
    .byte $53, $FE, $49, $4E, $56, $49, $53, $49, $42, $4C, $45, $20, $46, $4F, $45, $53
    .byte $2E, $FE, $50, $41, $4C, $41, $43, $45, $20, $53, $49, $58, $20, $48, $4F, $4C
    .byte $44, $53, $FE, $49, $54, $2E, $FF

.export text_nabooru_hint_1
text_nabooru_hint_1:
    .byte $54, $48, $55, $4E, $44, $45, $52, $20, $49, $53, $20, $54, $48, $45, $20, $4B
    .byte $45, $59, $FE, $54, $4F, $20, $54, $48, $45, $20, $47, $52, $45, $41, $54, $FE
    .byte $50, $41, $4C, $41, $43, $45, $20, $47, $55, $41, $52, $44, $49, $41, $4E, $2E
    .byte $FF

.export text_nabooru_spell_1
text_nabooru_spell_1:
    .byte $54, $48, $45, $20, $54, $48, $55, $4E, $44, $45, $52, $20, $53, $50, $45, $4C
    .byte $4C, $FE, $49, $53, $20, $54, $48, $45, $20, $4D, $4F, $53, $54, $FE, $50, $4F
    .byte $57, $45, $52, $46, $55, $4C, $20, $4D, $41, $47, $49, $43, $2E, $FF

; --- town_kasuto_hidden ---
.export text_kasuto_elder_1
text_kasuto_elder_1:
    .byte $59, $4F, $55, $20, $46, $4F, $55, $4E, $44, $20, $54, $48, $45, $FE, $48, $49
    .byte $44, $44, $45, $4E, $20, $54, $4F, $57, $4E, $21, $FE, $54, $41, $4B, $45, $20
    .byte $54, $48, $49, $53, $20, $4D, $41, $47, $49, $43, $FE, $4B, $45, $59, $2E, $FF

.export text_kasuto_hint_1
text_kasuto_hint_1:
    .byte $54, $48, $45, $20, $4D, $41, $47, $49, $43, $20, $4B, $45, $59, $20, $4F, $50
    .byte $45, $4E, $53, $FE, $41, $4C, $4C, $20, $4C, $4F, $43, $4B, $45, $44, $20, $44
    .byte $4F, $4F, $52, $53, $2E, $FF

; --- Signs ---
.export text_sign_north
text_sign_north:
    .byte $4E, $4F, $52, $54, $48, $20, $54, $4F, $20, $54, $48, $45, $FE, $53, $4C, $45
    .byte $45, $50, $49, $4E, $47, $20, $50, $41, $4C, $41, $43, $45, $FF

.export text_sign_cave
text_sign_cave:
    .byte $43, $41, $56, $45, $20, $41, $48, $45, $41, $44, $2E, $FE, $42, $52, $49, $4E
    .byte $47, $20, $41, $20, $43, $41, $4E, $44, $4C, $45, $2E, $FF

.export text_sign_sea
text_sign_sea:
    .byte $54, $48, $45, $20, $47, $52, $45, $41, $54, $20, $53, $45, $41, $2E, $FE, $4F
    .byte $4E, $4C, $59, $20, $41, $20, $52, $41, $46, $54, $20, $43, $41, $4E, $FE, $43
    .byte $52, $4F, $53, $53, $2E, $FF

.export text_sign_mountain
text_sign_mountain:
    .byte $44, $45, $41, $54, $48, $20, $4D, $4F, $55, $4E, $54, $41, $49, $4E, $2E, $FE
    .byte $54, $55, $52, $4E, $20, $42, $41, $43, $4B, $20, $49, $46, $20, $59, $4F, $55
    .byte $FE, $41, $52, $45, $20, $4E, $4F, $54, $20, $52, $45, $41, $44, $59, $2E, $FF

.export text_sign_palace
text_sign_palace:
    .byte $41, $20, $50, $41, $4C, $41, $43, $45, $20, $4C, $49, $45, $53, $FE, $57, $49
    .byte $54, $48, $49, $4E, $2E, $FF

; --- Item Pickups ---
.export text_item_candle
text_item_candle:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $43, $41, $4E, $44
    .byte $4C, $45, $21, $FE, $49, $54, $20, $4C, $49, $47, $48, $54, $53, $20, $44, $41
    .byte $52, $4B, $FE, $43, $41, $56, $45, $53, $2E, $FF

.export text_item_hammer
text_item_hammer:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $48, $41, $4D, $4D
    .byte $45, $52, $21, $FE, $42, $52, $45, $41, $4B, $20, $52, $4F, $43, $4B, $53, $20
    .byte $41, $4E, $44, $FE, $42, $4F, $55, $4C, $44, $45, $52, $53, $2E, $FF

.export text_item_raft
text_item_raft:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $52, $41, $46, $54
    .byte $21, $FE, $43, $52, $4F, $53, $53, $20, $54, $48, $45, $20, $47, $52, $45, $41
    .byte $54, $FE, $53, $45, $41, $2E, $FF

.export text_item_boots
text_item_boots:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $42, $4F, $4F, $54
    .byte $53, $21, $FE, $57, $41, $4C, $4B, $20, $4F, $4E, $20, $53, $48, $41, $4C, $4C
    .byte $4F, $57, $FE, $57, $41, $54, $45, $52, $2E, $FF

.export text_item_flute
text_item_flute:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $46, $4C, $55, $54
    .byte $45, $21, $FE, $43, $41, $4C, $4C, $20, $54, $48, $45, $20, $57, $48, $49, $52
    .byte $4C, $57, $49, $4E, $44, $FE, $54, $4F, $20, $54, $52, $41, $56, $45, $4C, $20
    .byte $46, $41, $52, $2E, $FF

.export text_item_cross
text_item_cross:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $43, $52, $4F, $53
    .byte $53, $21, $FE, $53, $45, $45, $20, $49, $4E, $56, $49, $53, $49, $42, $4C, $45
    .byte $FE, $45, $4E, $45, $4D, $49, $45, $53, $2E, $FF

.export text_item_glove
text_item_glove:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $47, $4C, $4F, $56
    .byte $45, $21, $FE, $50, $49, $43, $4B, $20, $55, $50, $20, $41, $4E, $44, $20, $54
    .byte $48, $52, $4F, $57, $FE, $4F, $42, $4A, $45, $43, $54, $53, $2E, $FF

.export text_item_magic_key
text_item_magic_key:
    .byte $59, $4F, $55, $20, $47, $4F, $54, $20, $54, $48, $45, $20, $4D, $41, $47, $49
    .byte $43, $FE, $4B, $45, $59, $21, $20, $41, $4C, $4C, $20, $44, $4F, $4F, $52, $53
    .byte $FE, $4F, $50, $45, $4E, $20, $42, $45, $46, $4F, $52, $45, $20, $59, $4F, $55
    .byte $2E, $FF

.export text_item_heart_container
text_item_heart_container:
    .byte $48, $45, $41, $52, $54, $20, $43, $4F, $4E, $54, $41, $49, $4E, $45, $52, $21
    .byte $FE, $59, $4F, $55, $52, $20, $4C, $49, $46, $45, $20, $46, $4F, $52, $43, $45
    .byte $FE, $47, $52, $4F, $57, $53, $20, $53, $54, $52, $4F, $4E, $47, $45, $52, $2E
    .byte $FF

.export text_item_magic_container
text_item_magic_container:
    .byte $4D, $41, $47, $49, $43, $20, $43, $4F, $4E, $54, $41, $49, $4E, $45, $52, $21
    .byte $FE, $59, $4F, $55, $52, $20, $4D, $41, $47, $49, $43, $20, $50, $4F, $57, $45
    .byte $52, $FE, $45, $58, $50, $41, $4E, $44, $53, $2E, $FF

.export text_item_sword_white
text_item_sword_white:
    .byte $54, $48, $45, $20, $57, $48, $49, $54, $45, $20, $53, $57, $4F, $52, $44, $21
    .byte $FE, $49, $54, $53, $20, $42, $4C, $41, $44, $45, $20, $47, $4C, $45, $41, $4D
    .byte $53, $FE, $57, $49, $54, $48, $20, $50, $4F, $57, $45, $52, $2E, $FF

.export text_item_sword_magic
text_item_sword_magic:
    .byte $54, $48, $45, $20, $4D, $41, $47, $49, $43, $41, $4C, $20, $53, $57, $4F, $52
    .byte $44, $21, $FE, $55, $4C, $54, $49, $4D, $41, $54, $45, $20, $42, $4C, $41, $44
    .byte $45, $20, $4F, $46, $FE, $43, $4F, $55, $52, $41, $47, $45, $2E, $FF

.export text_item_ring_blue
text_item_ring_blue:
    .byte $54, $48, $45, $20, $42, $4C, $55, $45, $20, $52, $49, $4E, $47, $21, $FE, $44
    .byte $41, $4D, $41, $47, $45, $20, $49, $53, $20, $48, $41, $4C, $56, $45, $44, $2E
    .byte $FF

.export text_item_ring_red
text_item_ring_red:
    .byte $54, $48, $45, $20, $52, $45, $44, $20, $52, $49, $4E, $47, $21, $FE, $44, $41
    .byte $4D, $41, $47, $45, $20, $49, $53, $20, $47, $52, $45, $41, $54, $4C, $59, $FE
    .byte $52, $45, $44, $55, $43, $45, $44, $2E, $FF

; --- Story ---
.export text_intro_1
text_intro_1:
    .byte $4C, $4F, $4E, $47, $20, $41, $47, $4F, $20, $57, $48, $45, $4E, $FE, $48, $59
    .byte $52, $55, $4C, $45, $20, $57, $41, $53, $20, $4F, $4E, $45, $FE, $4C, $41, $4E
    .byte $44, $20, $41, $20, $47, $52, $45, $41, $54, $20, $4B, $49, $4E, $47, $FE, $48
    .byte $45, $4C, $44, $20, $54, $48, $45, $20, $54, $52, $49, $46, $4F, $52, $43, $45
    .byte $2E, $FF

.export text_intro_2
text_intro_2:
    .byte $42, $45, $46, $4F, $52, $45, $20, $48, $49, $53, $20, $44, $45, $41, $54, $48
    .byte $FE, $48, $45, $20, $48, $49, $44, $20, $54, $48, $45, $20, $54, $52, $49, $46
    .byte $4F, $52, $43, $45, $FE, $4F, $46, $20, $43, $4F, $55, $52, $41, $47, $45, $20
    .byte $49, $4E, $20, $54, $48, $45, $FE, $47, $52, $45, $41, $54, $20, $50, $41, $4C
    .byte $41, $43, $45, $2E, $FF

.export text_intro_3
text_intro_3:
    .byte $41, $20, $53, $4C, $45, $45, $50, $49, $4E, $47, $20, $53, $50, $45, $4C, $4C
    .byte $FE, $57, $41, $53, $20, $43, $41, $53, $54, $20, $4F, $4E, $20, $50, $52, $49
    .byte $4E, $43, $45, $53, $53, $FE, $5A, $45, $4C, $44, $41, $2E, $20, $53, $48, $45
    .byte $20, $53, $4C, $45, $45, $50, $53, $FE, $49, $4E, $20, $54, $48, $45, $20, $4E
    .byte $4F, $52, $54, $48, $20, $50, $41, $4C, $41, $43, $45, $2E, $FF

.export text_intro_4
text_intro_4:
    .byte $4F, $4E, $4C, $59, $20, $54, $48, $45, $20, $54, $52, $49, $46, $4F, $52, $43
    .byte $45, $FE, $4F, $46, $20, $43, $4F, $55, $52, $41, $47, $45, $20, $43, $41, $4E
    .byte $FE, $42, $52, $45, $41, $4B, $20, $54, $48, $45, $20, $53, $50, $45, $4C, $4C
    .byte $2E, $FE, $4C, $49, $4E, $4B, $20, $4D, $55, $53, $54, $20, $46, $49, $4E, $44
    .byte $20, $49, $54, $2E, $FF

.export text_ending_1
text_ending_1:
    .byte $54, $48, $45, $20, $54, $52, $49, $46, $4F, $52, $43, $45, $20, $4F, $46, $FE
    .byte $43, $4F, $55, $52, $41, $47, $45, $20, $53, $48, $49, $4E, $45, $53, $21, $FE
    .byte $5A, $45, $4C, $44, $41, $20, $41, $57, $41, $4B, $45, $4E, $53, $20, $46, $52
    .byte $4F, $4D, $FE, $48, $45, $52, $20, $4C, $4F, $4E, $47, $20, $53, $4C, $45, $45
    .byte $50, $2E, $FF

.export text_ending_2
text_ending_2:
    .byte $50, $45, $41, $43, $45, $20, $52, $45, $54, $55, $52, $4E, $53, $20, $54, $4F
    .byte $FE, $48, $59, $52, $55, $4C, $45, $2E, $20, $54, $48, $45, $20, $48, $45, $52
    .byte $4F, $FE, $4C, $49, $4E, $4B, $20, $48, $41, $53, $20, $53, $41, $56, $45, $44
    .byte $20, $54, $48, $45, $FE, $50, $52, $49, $4E, $43, $45, $53, $53, $21, $FF

.export text_game_over
text_game_over:
    .byte $52, $45, $54, $55, $52, $4E, $20, $4F, $46, $20, $47, $41, $4E, $4F, $4E, $FF

.export text_title_screen
text_title_screen:
    .byte $5A, $45, $4C, $44, $41, $20, $32, $42, $FE, $54, $48, $45, $20, $41, $44, $56
    .byte $45, $4E, $54, $55, $52, $45, $20, $4F, $46, $FE, $4C, $49, $4E, $4B, $FE, $50
    .byte $52, $45, $53, $53, $20, $53, $54, $41, $52, $54, $FF

; --- String Pointer Table ---
; Total: 46 strings, 2124 bytes
.export text_table_lo, text_table_hi
text_table_lo:
    .byte <text_rauru_elder_1
    .byte <text_rauru_healer_1
    .byte <text_rauru_hint_1
    .byte <text_rauru_shop_1
    .byte <text_rauru_woman_1
    .byte <text_ruto_elder_1
    .byte <text_ruto_hint_1
    .byte <text_ruto_spell_1
    .byte <text_saria_elder_1
    .byte <text_saria_hint_1
    .byte <text_saria_spell_1
    .byte <text_mido_elder_1
    .byte <text_mido_hint_1
    .byte <text_mido_spell_1
    .byte <text_nabooru_elder_1
    .byte <text_nabooru_hint_1
    .byte <text_nabooru_spell_1
    .byte <text_kasuto_elder_1
    .byte <text_kasuto_hint_1
    .byte <text_sign_north
    .byte <text_sign_cave
    .byte <text_sign_sea
    .byte <text_sign_mountain
    .byte <text_sign_palace
    .byte <text_item_candle
    .byte <text_item_hammer
    .byte <text_item_raft
    .byte <text_item_boots
    .byte <text_item_flute
    .byte <text_item_cross
    .byte <text_item_glove
    .byte <text_item_magic_key
    .byte <text_item_heart_container
    .byte <text_item_magic_container
    .byte <text_item_sword_white
    .byte <text_item_sword_magic
    .byte <text_item_ring_blue
    .byte <text_item_ring_red
    .byte <text_intro_1
    .byte <text_intro_2
    .byte <text_intro_3
    .byte <text_intro_4
    .byte <text_ending_1
    .byte <text_ending_2
    .byte <text_game_over
    .byte <text_title_screen
text_table_hi:
    .byte >text_rauru_elder_1
    .byte >text_rauru_healer_1
    .byte >text_rauru_hint_1
    .byte >text_rauru_shop_1
    .byte >text_rauru_woman_1
    .byte >text_ruto_elder_1
    .byte >text_ruto_hint_1
    .byte >text_ruto_spell_1
    .byte >text_saria_elder_1
    .byte >text_saria_hint_1
    .byte >text_saria_spell_1
    .byte >text_mido_elder_1
    .byte >text_mido_hint_1
    .byte >text_mido_spell_1
    .byte >text_nabooru_elder_1
    .byte >text_nabooru_hint_1
    .byte >text_nabooru_spell_1
    .byte >text_kasuto_elder_1
    .byte >text_kasuto_hint_1
    .byte >text_sign_north
    .byte >text_sign_cave
    .byte >text_sign_sea
    .byte >text_sign_mountain
    .byte >text_sign_palace
    .byte >text_item_candle
    .byte >text_item_hammer
    .byte >text_item_raft
    .byte >text_item_boots
    .byte >text_item_flute
    .byte >text_item_cross
    .byte >text_item_glove
    .byte >text_item_magic_key
    .byte >text_item_heart_container
    .byte >text_item_magic_container
    .byte >text_item_sword_white
    .byte >text_item_sword_magic
    .byte >text_item_ring_blue
    .byte >text_item_ring_red
    .byte >text_intro_1
    .byte >text_intro_2
    .byte >text_intro_3
    .byte >text_intro_4
    .byte >text_ending_1
    .byte >text_ending_2
    .byte >text_game_over
    .byte >text_title_screen
