; ==========================================================
; Palettes Data — auto-generated by json2asm.py
; Source: assets/palettes/palace.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

.export palace_bg_palettes
palace_bg_palettes:
    .byte $0F, $02, $11, $20  ; palette 0
    .byte $0F, $06, $17, $27  ; palette 1
    .byte $0F, $04, $14, $24  ; palette 2
    .byte $0F, $06, $16, $26  ; palette 3

.export palace_spr_palettes
palace_spr_palettes:
    .byte $0F, $29, $19, $30  ; palette 0
    .byte $0F, $12, $02, $30  ; palette 1
    .byte $0F, $16, $06, $30  ; palette 2
    .byte $0F, $27, $17, $30  ; palette 3
