; ==========================================================
; Palettes Data — auto-generated by json2asm.py
; Source: assets/palettes/sprites.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

.export sprite_palettes
sprite_palettes:
    .byte $0F, $29, $19, $30  ; palette 0
    .byte $0F, $12, $02, $30  ; palette 1
    .byte $0F, $16, $06, $30  ; palette 2
    .byte $0F, $27, $17, $30  ; palette 3
