; ==========================================================
; Palettes Data — auto-generated by json2asm.py
; Source: assets/palettes/town.json
; DO NOT EDIT — regenerate from JSON source
; ==========================================================

.segment "PRG_FIXED_C"

.export town_bg_palettes
town_bg_palettes:
    .byte $0F, $07, $17, $27  ; palette 0
    .byte $0F, $06, $16, $26  ; palette 1
    .byte $0F, $09, $19, $29  ; palette 2
    .byte $0F, $00, $10, $20  ; palette 3

.export town_spr_palettes
town_spr_palettes:
    .byte $0F, $29, $19, $30  ; palette 0
    .byte $0F, $12, $02, $30  ; palette 1
    .byte $0F, $16, $06, $30  ; palette 2
    .byte $0F, $27, $17, $30  ; palette 3
